AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function. Lambda SAM template using 256mb with 1 minute timeout.
Resources:
  LambdaCodeTagsSSM:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 60
      Role: 'arn:aws:iam::111111111111:role/LambdaMasterExecutionRole'
      Environment:
        Variables:
          INSTANCE_TAGS: 'K8s,AccountB, testinLambda, Account2,WebServerGroup,'
